from selenium.webdriver.common.by import By


class RosterTrackerLocatorsL1:
    RosterTrackerHeading = (By.XPATH, "//h6[@class='MuiTypography-root MuiTypography-h6 css-8exomn']")
    RefreshBtn = (By.XPATH, '//*[@id="root"]/div/main/div[2]/div[1]/div[1]/div/div[2]/div[2]/div/button/span/svg')
    ResetBtn = (By.XPATH, '//*[@id="root"]/div/main/div[2]/div[1]/div[1]/div/div[2]/button')
    L1DownloadBtn = (By.XPATH, '//button[@class="MuiButtonBase-root MuiButton-root MuiLoadingButton-root MuiButton-outlined MuiButton-outlinedSecondary MuiButton-sizeMedium MuiButton-outlinedSizeMedium MuiButton-root MuiLoadingButton-root MuiButton-outlined MuiButton-outlinedSecondary MuiButton-sizeMedium MuiButton-outlinedSizeMedium css-56hqex"]')
    L1DownloadSuccessPopUp = (By.XPATH, "/html/body/div[4]/div[3]/div/div/div[3]/p")
    L1OkBtnOnDownloadSuccessPopup = (By.XPATH, "/html/body/div[4]/div[3]/div/div/div[4]/div/button")
    RosterDetailsRow = (By.XPATH, "//p[@class='MuiTypography-root MuiTypography-body1 css-xvjzky' and text()='{}']") # this is the first occurrence
    TicketNoFilter = (By.XPATH, '/html/body/div[1]/div/main/div[2]/div[1]/div[2]/div/div[1]/div/div/div/input')
    TicketNoFilterDropDown = (By.XPATH, "//div[@class='MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-1 css-tuxzvu']//div[1]//div[1]//div[1]//div[1]//div[1]//button[1]//*[name()='svg']//*[name()='path' and contains(@d,'M7 10l5 5 ')]")
    ProviderGroupFilter = (By.XPATH, "/html/body/div[1]/div/main/div[2]/div[1]/div[2]/div/div[2]/div/div/div/input")
    ProviderGroupFilterDropDown = (By.XPATH, "//div[@class='MuiBox-root css-542elh']//div[2]//div[1]//div[1]//div[1]//div[1]//button[1]//*[name()='svg']//*[name()='path' and contains(@d,'M7 10l5 5 ')]")
    DateFilter = (By.XPATH, "/html/body/div[1]/div/main/div[2]/div[1]/div[2]/div/div[3]/div/div/div/div[1]/input")
    RemoveDateFromFilter = (By.XPATH, '//*[@id="root"]/div/main/div[2]/div[1]/div[2]/div/div[3]/div/div/div/div[2]/span')
    MarketFilter = (By.XPATH, "/html/body/div[1]/div/main/div[2]/div[1]/div[2]/div/div[4]/div/div/div/input")
    MarketFilterDropDown = (By.XPATH, "//div[4]//div[1]//div[1]//div[1]//div[1]//button[1]//*[name()='svg']//*[name()='path' and contains(@d,'M7 10l5 5 ')]")
    LOBFilter = (By.XPATH, "/html/body/div[1]/div/main/div[2]/div[1]/div[2]/div/div[5]/div/div/div/input")
    LOBFilterDropDown = (By.XPATH, "//div[5]//div[1]//div[1]//div[1]//div[1]//button[1]//*[name()='svg']")
    TINFilter = (By.XPATH, "/html/body/div[1]/div/main/div[2]/div[1]/div[2]/div/div[6]/div/div/div/input")
    TINFilterDropDown = (By.XPATH, "//div[6]//div[1]//div[1]//div[1]//div[1]//button[1]//*[name()='svg']")
    StatusFilter = (By.XPATH, "/html/body/div[1]/div/main/div[2]/div[1]/div[2]/div/div[7]/div/div/div/input")
    StatusFilterDropDown = (By.XPATH, "//div[7]//div[1]//div[1]//div[1]//div[1]//button[1]//*[name()='svg']//*[name()='path' and contains(@d,'M7 10l5 5 ')]")
    SourceSystemFilter = (By.XPATH, "//label[@class='MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-sizeSmall MuiInputLabel-outlined MuiFormLabel-colorPrimary MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-sizeSmall MuiInputLabel-outlined css-1ju8vyi' and text()='Source System']")
    SourceSystemFilterDropDown = (By.XPATH, "//div[8]//div[1]//div[1]//div[1]//div[1]//button[1]//*[name()='svg']")
    PaginationDropDown = (By.XPATH, "//div[@aria-label='Without label']")
    PaginationNavigateToPreviousPage = (By.XPATH, '//*[@id="root"]/div/main/div[2]/div[2]/div[1]/div/div/div[2]/nav/ul/li[1]/button')
    PaginationNavigateToNextPage = (By.XPATH, '//*[@id="root"]/div/main/div[2]/div[2]/div[1]/div/div/div[2]/nav/ul/li[9]/button')
    GenAIChatBot = (By.XPATH, "//p[@class='MuiTypography-root MuiTypography-body1 css-ysgvth']")
    TNDropDownFirstDetails = (By.XPATH, "//li[@id=':rka:-option-0']")
    TicketNoReadTableData = (By.XPATH, "//p[@class='MuiTypography-root MuiTypography-body1 css-xvjzky']")
    TicketNoWriteTableData = (By.XPATH, "//p[@class='MuiTypography-root MuiTypography-body1 css-xvjzky' and text()='{}']")
    PGDropDowFirstDetails = (By.XPATH, "//li[@id=':r1lo:-option-0']")
    MarketDisplayedOnTableDetails = (By.XPATH, '//*[@id="root"]/div/main/div[2]/div[2]/div[1]/div/div/div[1]/table/tbody/tr[1]/td[3]')
    MarketDropDownFirstDetails = (By.XPATH, "//li[@id=':r2c1:-option-0']")
    # This element can be used to replace Roster Status, TicketNo, Market, Records in Roster, Records in scope, etc.
    ReadTableDetailsOnXpath = (By.XPATH, "//td[@class='MuiTableCell-root MuiTableCell-body MuiTableCell-sizeSmall css-19115l7']")
    PageSizeTen = (By.XPATH, "//p[@class='MuiTypography-root MuiTypography-body2 css-6ovtyp' and text()='10']")
    PageSizeTwenty = (By.XPATH, "//p[@class='MuiTypography-root MuiTypography-body2 css-6ovtyp' and text()='20']")
    PageSizeThirty = (By.XPATH, "//p[@class='MuiTypography-root MuiTypography-body2 css-6ovtyp' and text()='30']")
    PageSizeForty = (By.XPATH, "//p[@class='MuiTypography-root MuiTypography-body2 css-6ovtyp' and text()='40']")
    PageSizeFifty = (By.XPATH, "//p[@class='MuiTypography-root MuiTypography-body2 css-6ovtyp' and text()='50']")
    TableHeadersOnTracker = (By.XPATH, "//div[@class='MuiBox-root css-lvyu5j']")
    TableSortOff = (By.XPATH, "//div[@class='MuiBox-root css-1bicmub']")
    TableSortAscendingDescending = (By.XPATH, "//div[@class='MuiBox-root css-ryfr2d']")
    SortTicketNoTableHeader = (By.XPATH, "/html/body/div[1]/div/main/div[2]/div[2]/div[1]/div/div/div[1]/table/thead/tr/th[1]/div/div[2]/div")
    SortRosterStatusTableHeader = (By.XPATH, '')
    RosterStatusTDReadData = (By.XPATH, "//div[@class='MuiBox-root css-v7v99c']")
    Last7DaysButton = (By.XPATH, "/html/body/div[4]/div/div/div/div[2]/div[1]/div/div[1]/button")
    Last15DaysButton = (By.XPATH, "/html/body/div[4]/div/div/div/div[2]/div[1]/div/div[2]/button")
    Last20DaysButton = (By.XPATH, "/html/body/div[4]/div/div/div/div[2]/div[1]/div/div[3]/button")
    Last30DaysButton = (By.XPATH, "/html/body/div[4]/div/div/div/div[2]/div[1]/div/div[4]/button")
    DatePickerPopUp = (By.XPATH, "//div[@class='rs-picker-daterange-content']")
    DateRangeOnPopUp = (By.XPATH, "//div[@class='rs-picker-daterange-header']")
    OkButtonOnDatePickerPopUp = (By.XPATH, "/html/body/div[4]/div/div/div/div[2]/div[2]/div/button")


class RosterTrackerLocatorsL2:
    RosterTrackerHeading = (By.XPATH, "//h6[@class='MuiTypography-root MuiTypography-h6 css-19sb0h9']")
    L2DownloadBtn = (By.XPATH, "//button[normalize-space()='Download']")
    TicketNoLabel = (By.XPATH, "//h5[@class='MuiTypography-root MuiTypography-h5 css-1klh293']")
    FileStatusLabel = (By.XPATH, '//*[@id="root"]/div/main/div[2]/div[4]/div/div/div[1]/table/tbody/tr/td[3]/div/p')
    MarketLabelTD = (By.XPATH, '//*[@id="root"]/div/main/div[2]/div[4]/div/div/div[1]/table/tbody/tr/td[4]')
    MarketLabelHD = (By.XPATH, '//*[@id="root"]/div/main/div[2]/div[3]/div/div[2]/div[2]/p[1]')
    ReasonDescriptionTD = (By.XPATH, '//*[@id="root"]/div/main/div[2]/div[4]/div/div/div[1]/table/tbody/tr/td[12]/div/div')
    EditMappingBtn = (By.XPATH, "//img[@src='/Edit_Icon_Enable.svg']")
    refreshBtnL2 = (By.XPATH, "//button[@class='MuiButtonBase-root MuiButton-root MuiButton-link "
                              "MuiButton-linkSecondary MuiButton-sizeMedium MuiButton-linkSizeMedium MuiButton-root "
                              "MuiButton-link MuiButton-linkSecondary MuiButton-sizeMedium MuiButton-linkSizeMedium "
                              "css-lzkttt']//span[@class='MuiButton-startIcon MuiButton-iconSizeMedium "
                              "css-6xugel']//*[name()='svg']")
    FileNameLabelL2 = (By.XPATH, '//*[@id="root"]/div/main/div[2]/div[4]/div/div/div[1]/table/tbody/tr/td[2]/div/div/button')
    ActionsMenuL2 = (By.XPATH, "//*[name()='path' and contains(@d,'M12 8c1.1 ')]")
    RejectRosterUnderActionMenu = (By.XPATH, '//*[@id="long-menu"]/div[3]/ul/li[1]')
    StopRosterUnderActionMenu = (By.XPATH, '//*[@id="long-menu"]/div[3]/ul/li[5]')
    EditRosterUnderActionMenu = (By.XPATH, '//*[@id="long-menu"]/div[3]/ul/li[6]')
    RegenerateISFUnderActionMenu = (By.XPATH, '//*[@id="long-menu"]/div[3]/ul/li[2]')
    RegenerateQNXTUnderActionMenu = (By.XPATH, '//*[@id="long-menu"]/div[3]/ul/li[3]')


class PizzaTrackerL3:
    PLMNoLabelPizzaTracker = (By.XPATH,"/html/body/div[4]/div[3]/div/div/div[3]/div[1]/span[1]")
    ExpandPizzaTracker = (By.XPATH, "/html/body/div[4]/div[3]/div/div/div[3]/div[2]/div[2]/img")
    collapsePizzaTracker = (By.XPATH, "/html/body/div[4]/div[3]/div/div/div[3]/div[2]/div[4]/img")
    ActionMenuPizzaTracker = (By.XPATH, '//*[@id="long-button"]')
    RegenerateISFPizzaTracker = (By.XPATH, '//*[@id="long-menu"]/div[3]/ul/li[1]')
    RegenerateQNXTPizzaTracker = (By.XPATH, '//*[@id="long-menu"]/div[3]/ul/li[1]')
    DownloadTrackerReportBtn = (By.XPATH, '/html/body/div[4]/div[3]/div/div/div[3]/div[2]/span')
    ReleaseToQNXTBtn = (By.XPATH, '//*[@id=":r4ha:"]/div[2]/div[1]/button')
    SuccessImgOnRosterReceived = (By.XPATH, '/html/body/div[4]/div[3]/div/div/div[3]/div[2]/div[1]/div[1]/div/div/img[1]')
    SuccessImgOnMappingCompleted = (By.XPATH, '/html/body/div[4]/div[3]/div/div/div[3]/div[2]/div[1]/div[1]/div/div/img[1]')
    SuccessImgOnISF = (By.XPATH, '/html/body/div[4]/div[3]/div/div/div[3]/div[2]/div[1]/div[3]/div/div/img[1]')
    SuccessImgOnQNXT = (By.XPATH, '/html/body/div[4]/div[3]/div/div/div[3]/div[2]/div[1]/div[4]/div/div/img[1]')



class ApproveOrEditMappingL3:
    ApproveEditHeader = (By.XPATH, '/html/body/div[4]/div[3]/div/div/div[1]/h5')
    SheetsBtn = (By.XPATH, '/html/body/div[4]/div[3]/div/div/div[4]/div[1]/div/div/button[1]')
    ColumnMappingBtn = (By.XPATH, '/html/body/div[4]/div[3]/div/div/div[4]/div[1]/div/div/button[2]')
    DownloadColumnMappingBtn = (By.XPATH, '/html/body/div[4]/div[3]/div/div/div[1]/img')
    CancelBtn = (By.XPATH, '/html/body/div[4]/div[3]/div/div/div[5]/button')
    CancelBtnOnSave = (By.XPATH, "/html/body/div[5]/div[3]/div/div/div[3]/button[2]")
    SaveBtn = (By.XPATH, "/html/body/div[4]/div[3]/div/div/div[5]/div/button[1]")
    SaveBtnOnSave = (By.XPATH, "/html/body/div[5]/div[3]/div/div/div[3]/button[1]")
    ApproveBtn = (By.XPATH, "/html/body/div[4]/div[3]/div/div/div[5]/div/button[2]")
    ApproveBtnOnApprove = (By.XPATH, '/html/body/div[5]/div[3]/div/div/div[3]/button[1]')
    CloseBtnX = (By.XPATH, "/html/body/div[4]/div[3]/div/div/div[3]/img")
    ApprovedSucessMsg = (By.XPATH, "/html/body/div[5]/div[3]/div/div/div[2]/p/div")
    OkBtnOnApprove = (By.XPATH, '/html/body/div[5]/div[3]/div/div/div[3]/button[1]')
    EditMappingApprovedSuccessMsg = (By.XPATH, "/html/body/div[6]/div[3]/div/div/div[2]/p")
